# ---- REQUIRED ---- #
[telegram]
# Get this value from https://my.telegram.org/apps
api_id = 12012137 # Client API ID used for authentication
api_hash = "c6f685922e2f1aef58d7b3d8d5561ffb" # Client API hash used for authentication
# ---- OPTIONAL ---- #
[telegram.helper]
# Bot token used for helper
token = "7443146165:AAHxaOi5asGtqk_f82n9gYqBRTawNjBMawQ"  # Remove the '#'' and add your token to initialize

[bot]
# Mongodb url from https://cloud.mongodb.com/
db_uri = "mongodb+srv://sawyerkelly003:ultroud@cluster0.ejrkb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# ---- OPTIONAL ---- #
# Bot command prefix
prefix = "."

# How the bot responds to commands.
# Valid options: edit, reply, repost
response_mode = "reply"

# How the bot handles responses too long for one message by default.
# Note that this can be overridden on a per-command basis.
# Valid options: split, truncate
overflow_mode = "truncate"

# Maximum number of pages per message before truncation takes place.
# Only applicable if the overflow mode is "split".
# This is a sanity check to prevent abnormally long messages from making the bot spam
# and potentially getting your account banned/limited.
overflow_page_limit = 4

# Whether to redact sensitive information from messages the bot sends/responds to.
# "Sensitive information" is defined as the Telegram API ID and hash as well as the
# account's phone number.
redact_responses = true

# Colorlog setting
colorlog = true
